version: "3.9"

x-common-variables: &common-variables
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgrespw

services:
  backend:
    image: "cr.yandex/crpj359s4d2stuu9d49c/dex_backend:backend"
    ports:
      - "8081:8080"
    environment:
      <<: *common-variables
      # Specify memory target for JVM GC. Both -XmsXX and -XmxXX should have same value
      JAVA_TOOL_OPTIONS: "-Xms6G -Xmx6G"
      POSTGRES_URL: postgres:5432/dex
      # Micronaut framework settings
      MICRONAUT_SERVER_PORT: 8080
      MICRONAUT_SERVER_CORS_ENABLED: true
      # Dex' liteapi settings
      DEX_LITEAPI_IPV4: 1097649206
      DEX_LITEAPI_PORT: 29296
      DEX_LITEAPI_KEY: "p2tSiaeSqX978BxE5zLxuTQM06WVDErf5/15QToxMYA="
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      <<: *common-variables
      POSTGRES_DB: dex
