version: "3.9"

x-common-variables: &common-variables
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgrespw

services:
  backend:
    image: "ghcr.io/tegroton/dex_backend:latest"
    ports:
      - "8081:8080"
    environment:
      <<: *common-variables
      POSTGRES_URL: postgres:5432/dex
      #      DEX_LITEAPI_IPV4: 1097649206
      #      DEX_LITEAPI_PORT: 29296
      #      DEX_LITEAPI_KEY: "p2tSiaeSqX978BxE5zLxuTQM06WVDErf5/15QToxMYA="
      MICRONAUT_SERVER_PORT: 8080
      MICRONAUT_SERVER_CORS_ENABLED: true
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      <<: *common-variables
