ton-jetton:
  data:
    fift/exchange-data-example.fif
  func:
    - func/extlib.func
    - func/sqrt.func
    - func/text-utils.func
    - func/fee-calculation.func
    - func/exchange/ton-jetton/gas.func
    - func/exchange/constants.func
    - func/utils.func
    - func/exchange/ton-jetton/globals.func
    - func/exchange/fees.func
    - func/exchange/utils.func
    - func/exchange/jetton-utils.func
    - func/exchange/liquidity-utils.func
    - func/exchange/ton-jetton/liquidity.func
    - func/exchange/swap-utils.func
    - func/exchange/ton-jetton/swap.func
    - func/exchange/ton-jetton/main.func
  tests:
    - tests/exchange-test.func

#jetton-jetton:
#  data:
#    fift/data.fif
#  func:
#    - func/exchange/main.func
#  tests:
#    - tests/exchange-test.func


#lp-wallet:
#  func:
#    - func/extlib.func
#    - func/exchange/constants.func
#    - func/utils.func
#    - func/exchange/jetton-utils.func
#    - func/exchange/lp-wallet/main.func
