name: Backend docker container

on:
  push:
    branches: [ master, backend ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Make sure gradlew is executable
        run: chmod +x gradlew

      - name: Build and push image with Gradle + Jib
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: |
            jib -Djib.to.image=ghcr.io/TegroTON/DEX:latest \
            -Djib.to.auth.username=${{ github.actor }} \
            -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
